CONTIKI_PROJECT = ADC_example SHT2x_example bmp085_example bma180_example hmc5883l_example test-button lea_6t_example lsm330dlc_example example-coffee example-LSM330DLC amy_6m_example

all: $(CONTIKI_PROJECT)
#UIP_CONF_IPV6=1

APPS = serial-shell shell-time

CONTIKI = ../..
include $(CONTIKI)/Makefile.include




