CONTIKI = ../..

CONTIKI_PROJECT = hello-world test-button example-abc example-trickle example-coffee test-RTC test-kbi test-iopins test-i2c

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include

