CONTIKI = ../..

CONTIKI_PROJECT = hello-world test-button example-abc example-unicast example-trickle example-HMC5883L ex-broadcast-lqi ex-neighbours ex-mag report-top3

all: $(CONTIKI_PROJECT)

CONTIKI_SOURCEFILES += myneighbours.c

include $(CONTIKI)/Makefile.include

