Contiki 2.6: platform/OrisenPrime/dev/bmp085.c File Reference
bmp085.c File Reference
This file contains all function implementations for the BMP085 API.
#include "bmp085.h"
#include "lib/sensors.h"
#include "i2c.h"
Functions
int bmp085_init (bmp085_t *bmp085)
initialize BMP085 / SMD500
int bmp085_get_cal_param (void)
read out parameters cal_param from BMP085 memory
int smd500_get_cal_param (void)
read out parameters cal_param from SMD500 memory This routine generates parameters from bitsliced data
short bmp085_get_temperature (unsigned long ut)
calculate temperature from ut ut was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085
long bmp085_get_pressure (unsigned long up)
calculate pressure from up up was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085 In case of SMD500 value averaging is done in this function, in case of BMP085 averaging is done through oversampling by the sensor IC
unsigned short bmp085_get_ut ()
read out ut for temperature conversion
unsigned long bmp085_get_up ()
read out up for pressure conversion depending on the oversampling ratio setting up can be 16 to 19 bit
Variables
bmp085_t * p_bmp085 = 0
pointer to SMD500 / BMP085 device area
Detailed Description
This file contains all function implementations for the BMP085 API.
Details.
Definition in file bmp085.c.
Function Documentation
int bmp085_get_cal_param (void)
read out parameters cal_param from BMP085 memory
Returns:
result of communication routines
Definition at line 179 of file bmp085.c.
Referenced by bmp085_init().
long bmp085_get_pressure (unsigned long up)
calculate pressure from up up was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085 In case of SMD500 value averaging is done in this function, in case of BMP085 averaging is done through oversampling by the sensor IC
Parameters:
ut parameter ut read from device
Returns:
temperature in steps of 1.0 Pa
See also:
bmp085_read_up()
Definition at line 277 of file bmp085.c.
short bmp085_get_temperature (unsigned long ut)
calculate temperature from ut ut was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085
Parameters:
ut parameter ut read from device
Returns:
temperature in steps of 0.1 deg celsius
See also:
bmp085_read_ut()
Definition at line 235 of file bmp085.c.
unsigned long bmp085_get_up (void)
read out up for pressure conversion depending on the oversampling ratio setting up can be 16 to 19 bit
Returns:
up parameter that represents the uncompensated pressure value
Definition at line 361 of file bmp085.c.
unsigned short bmp085_get_ut (void)
read out ut for temperature conversion
Returns:
ut parameter that represents the uncompensated temperature sensors conversion value
Definition at line 326 of file bmp085.c.
int bmp085_init (bmp085_t * bmp085)
initialize BMP085 / SMD500
BMP085_init.
This function initializes the BMP085 pressure sensor/ the successor SMD500 is also supported. The function automatically detects the sensor type and stores this for all future communication and calculation steps
Parameters:
*bmp085_t pointer to bmp085 device data structure
Returns:
result of communication routines
Definition at line 99 of file bmp085.c.
References bmp085_get_cal_param(), and smd500_get_cal_param().
int smd500_get_cal_param (void)
read out parameters cal_param from SMD500 memory This routine generates parameters from bitsliced data
Returns:
result of communication routines
Definition at line 211 of file bmp085.c.
Referenced by bmp085_init().