Contiki 2.6: platform/OrisenPrime/dev/include/bmp085.h File Reference
bmp085.h File Reference
BMP085 Pressure Sensor API Copyright (C) 2009 Bosch Sensortec GmbH.
Data Structures
struct bmp085_smd500_calibration_param_t
this structure holds all device specific calibration parameters
struct bmp085_t
BMP085 image registers data structure.
Defines
#define BMP085_BUS_WR_RETURN_TYPE char
define for used read and write macros
#define BMP085_BUS_WR_PARAM_TYPES unsigned char,unsigned char,unsigned char *,unsigned char
defines the calling parameter types of the BMP085_WR_FUNCTION
#define BMP085_BUS_WR_PARAM_ORDER device_addr, register_addr, register_data, write_length
links the order of parameters defined in BMP085_BUS_WR_PARAM_TYPE to function calls used inside the API
#define BMP085_BUS_RD_RETURN_TYPE char
defines the return parameter type of the BMP085_WR_FUNCTION
#define BMP085_BUS_RD_PARAM_TYPES unsigned char, unsigned char, unsigned char *, unsigned char
defines the calling parameter types of the BMP085_WR_FUNCTION
#define BMP085_BUS_RD_PARAM_ORDER device_addr, register_addr, register_data, read_length
links the order of parameters defined in BMP085_BUS_WR_PARAM_TYPE to function calls used inside the API
Functions
int bmp085_init (bmp085_t *)
BMP085_init.
short bmp085_get_temperature (unsigned long ut)
calculate temperature from ut ut was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085
long bmp085_get_pressure (unsigned long up)
calculate pressure from up up was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085 In case of SMD500 value averaging is done in this function, in case of BMP085 averaging is done through oversampling by the sensor IC
unsigned short bmp085_get_ut (void)
read out ut for temperature conversion
unsigned long bmp085_get_up (void)
read out up for pressure conversion depending on the oversampling ratio setting up can be 16 to 19 bit
int bmp085_get_cal_param (void)
read out parameters cal_param from BMP085 memory
int smd500_get_cal_param (void)
read out parameters cal_param from SMD500 memory This routine generates parameters from bitsliced data
Detailed Description
BMP085 Pressure Sensor API Copyright (C) 2009 Bosch Sensortec GmbH.
Header file for all #define constants and function prototypes.
Introduction
BMP085 digital Altimeter Programming Interface The BMP085 API enables quick access to Bosch Sensortec's digital altimeter. The only mandatory steps are:
1. linking the target application's communication functions to the API (BMP085_WR_FUNC_PTR, BMP085_RD_FUNC_PTR)
2. calling the bmp085_init() routine, which initializes all necessary data structures for using all functions
Disclaimer
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License and the following stipulations. The Apache License , Version 2.0 is applicable unless otherwise stated by the stipulations of the disclaimer below.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Disclaimer
Common: This Work is developed for the consumer goods industry. It may only be used within the parameters of the respective valid product data sheet. The Work provided with the express understanding that there is no warranty of fitness for a particular purpose. It is not fit for use in life-sustaining, safety or security sensitive systems or any system or device that may lead to bodily harm or property damage if the system or device malfunctions. In addition, the Work is not fit for use in products which interact with motor vehicle systems. The resale and/or use of the Work are at the purchaser’s own risk and his own responsibility. The examination of fitness for the intended use is the sole responsibility of the Purchaser.
The purchaser shall indemnify Bosch Sensortec from all third party claims, including any claims for incidental, or consequential damages, arising from any Work or Derivative Work use not covered by the parameters of the respective valid product data sheet or not approved by Bosch Sensortec and reimburse Bosch Sensortec for all costs in connection with such claims.
The purchaser must monitor the market for the purchased Work and Derivative Works, particularly with regard to product safety and inform Bosch Sensortec without delay of all security relevant incidents.
Engineering Samples are marked with an asterisk (*) or (e). Samples may vary from the valid technical specifications of the product series. They are therefore not intended or fit for resale to third parties or for use in end products. Their sole purpose is internal client testing. The testing of an engineering sample may in no way replace the testing of a product series. Bosch Sensortec assumes no liability for the use of engineering samples. By accepting the engineering samples, the Purchaser agrees to indemnify Bosch Sensortec from all claims arising from the use of engineering samples.
Special: This Work and any related information (hereinafter called "Information") is provided free of charge for the sole purpose to support your application work. The Woek and Information is subject to the following terms and conditions:
The Work is specifically designed for the exclusive use for Bosch Sensortec products by personnel who have special experience and training. Do not use this Work or Derivative Works if you do not have the proper experience or training. Do not use this Work or Derivative Works fot other products than Bosch Sensortec products.
The Information provided is believed to be accurate and reliable. Bosch Sensortec assumes no responsibility for the consequences of use of such Information nor for any infringement of patents or other rights of third parties which may result from its use. No license is granted by implication or otherwise under any patent or patent rights of Bosch. Specifications mentioned in the Information are subject to change without notice.
Definition in file bmp085.h.
Define Documentation
#define BMP085_BUS_RD_PARAM_ORDER device_addr, register_addr, register_data, read_length
links the order of parameters defined in BMP085_BUS_WR_PARAM_TYPE to function calls used inside the API
Definition at line 170 of file bmp085.h.
#define BMP085_BUS_RD_PARAM_TYPES unsigned char, unsigned char, unsigned char *, unsigned char
defines the calling parameter types of the BMP085_WR_FUNCTION
Definition at line 165 of file bmp085.h.
#define BMP085_BUS_RD_RETURN_TYPE char
defines the return parameter type of the BMP085_WR_FUNCTION
Definition at line 160 of file bmp085.h.
#define BMP085_BUS_WR_PARAM_ORDER device_addr, register_addr, register_data, write_length
links the order of parameters defined in BMP085_BUS_WR_PARAM_TYPE to function calls used inside the API
Definition at line 147 of file bmp085.h.
#define BMP085_BUS_WR_PARAM_TYPES unsigned char,unsigned char,unsigned char *,unsigned char
defines the calling parameter types of the BMP085_WR_FUNCTION
Definition at line 142 of file bmp085.h.
#define BMP085_BUS_WR_RETURN_TYPE char
define for used read and write macros
Define the calling convention of YOUR bus communication routine.
Note:
This includes types of parameters. This example shows the configuration for an SPI bus link. defines the return parameter type of the BMP085_WR_FUNCTION
Definition at line 137 of file bmp085.h.
Function Documentation
int bmp085_get_cal_param (void)
read out parameters cal_param from BMP085 memory
Returns:
result of communication routines
Definition at line 179 of file bmp085.c.
Referenced by bmp085_init().
long bmp085_get_pressure (unsigned long up)
calculate pressure from up up was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085 In case of SMD500 value averaging is done in this function, in case of BMP085 averaging is done through oversampling by the sensor IC
Parameters:
ut parameter ut read from device
Returns:
temperature in steps of 1.0 Pa
See also:
bmp085_read_up()
Definition at line 277 of file bmp085.c.
short bmp085_get_temperature (unsigned long ut)
calculate temperature from ut ut was read from the device via I2C and fed into the right calc path for either SMD500 or BMP085
Parameters:
ut parameter ut read from device
Returns:
temperature in steps of 0.1 deg celsius
See also:
bmp085_read_ut()
Definition at line 235 of file bmp085.c.
unsigned long bmp085_get_up (void)
read out up for pressure conversion depending on the oversampling ratio setting up can be 16 to 19 bit
Returns:
up parameter that represents the uncompensated pressure value
Definition at line 361 of file bmp085.c.
unsigned short bmp085_get_ut (void)
read out ut for temperature conversion
Returns:
ut parameter that represents the uncompensated temperature sensors conversion value
Definition at line 326 of file bmp085.c.
int bmp085_init (bmp085_t * bmp085)
BMP085_init.
input : Pointer to bmp085_t output: - return: result of communication function notes :
BMP085_init.
This function initializes the BMP085 pressure sensor/ the successor SMD500 is also supported. The function automatically detects the sensor type and stores this for all future communication and calculation steps
Parameters:
*bmp085_t pointer to bmp085 device data structure
Returns:
result of communication routines
Definition at line 99 of file bmp085.c.
References bmp085_get_cal_param(), and smd500_get_cal_param().
int smd500_get_cal_param (void)
read out parameters cal_param from SMD500 memory This routine generates parameters from bitsliced data
Returns:
result of communication routines
Definition at line 211 of file bmp085.c.
Referenced by bmp085_init().